/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    fields: Field;
    games: Game;
    registrations: Registration;
    admins: Admin;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      registrations: 'registrations';
    };
    fields: {
      games: 'games';
    };
    games: {
      registrations: 'registrations';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    fields: FieldsSelect<false> | FieldsSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    home: Home;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Admin & {
        collection: 'admins';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email?: string | null;
  profilePicture?: (string | null) | Media;
  otp?: {
    code?: string | null;
    expiration?: string | null;
  };
  phoneNumber: string;
  isVerified?: boolean | null;
  name?: string | null;
  city?: string | null;
  deletedAt?: string | null;
  registrations?: {
    docs?: (string | Registration)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: string;
  deletedAt?: string | null;
  game: string | Game;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: string;
  name: string;
  description?: string | null;
  startsAt: string;
  endsAt: string;
  price: number;
  maxPlayers: number;
  sport: 'soccer' | 'padel' | 'tennis' | 'basketball' | 'volleyball';
  field: string | Field;
  deletedAt?: string | null;
  registrations?: {
    docs?: (string | Registration)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fields".
 */
export interface Field {
  id: string;
  name: string;
  address: string;
  type: 'indoor' | 'outdoor' | 'hybrid' | 'other';
  flooring:
    | 'natural_grass'
    | 'artificial_turf'
    | 'hybrid_turf'
    | 'clay'
    | 'hard_court'
    | 'rubber'
    | 'polyurethane'
    | 'wood'
    | 'sand'
    | 'concrete'
    | 'other';
  sport: 'soccer' | 'padel' | 'tennis' | 'basketball' | 'volleyball' | 'multi_purpose' | 'other';
  amenities?:
    | (
        | 'parking'
        | 'restrooms'
        | 'changing_rooms'
        | 'showers'
        | 'equipment_rental'
        | 'lockers'
        | 'storage_space'
        | 'water_fountain'
        | 'vending_machines'
        | 'cafe'
        | 'seating_area'
        | 'first_aid_station'
        | 'wifi'
        | 'lighting'
        | 'scoreboard'
      )[]
    | null;
  deletedAt?: string | null;
  games?: {
    docs?: (string | Game)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'fields';
        value: string | Field;
      } | null)
    | ({
        relationTo: 'games';
        value: string | Game;
      } | null)
    | ({
        relationTo: 'registrations';
        value: string | Registration;
      } | null)
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  profilePicture?: T;
  otp?:
    | T
    | {
        code?: T;
        expiration?: T;
      };
  phoneNumber?: T;
  isVerified?: T;
  name?: T;
  city?: T;
  deletedAt?: T;
  registrations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fields_select".
 */
export interface FieldsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  type?: T;
  flooring?: T;
  sport?: T;
  amenities?: T;
  deletedAt?: T;
  games?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  price?: T;
  maxPlayers?: T;
  sport?: T;
  field?: T;
  deletedAt?: T;
  registrations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  deletedAt?: T;
  game?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero: {
    title: string;
    subtitle: string;
    description: string;
    buttonLabel: string;
    partners: {
      logo: string | Media;
      name: string;
      id?: string | null;
    }[];
  };
  nextGames: {
    title: string;
    sportCategories?:
      | {
          name: string;
          emoji: string;
          id?: string | null;
        }[]
      | null;
  };
  howItWorks: {
    title: string;
    subtitle: string;
    buttonLabel: string;
    steps: {
      icon: string | Media;
      title: string;
      description: string;
      id?: string | null;
    }[];
  };
  stats: {
    title: string;
    statistics: {
      value: number;
      label: string;
      description: string;
      id?: string | null;
    }[];
    image: string | Media;
  };
  testimonials: {
    title: string;
    reviews: {
      quote: string;
      author: string;
      image: string | Media;
      id?: string | null;
    }[];
  };
  cta: {
    title: string;
    subtitle: string;
    buttonLabel: string;
    sports: {
      name: string;
      image: string | Media;
      selected: boolean;
      id?: string | null;
    }[];
  };
  strangers: {
    title: string;
    strangers: {
      name: string;
      age: number;
      bio: string;
      sport: string;
      image: string | Media;
      id?: string | null;
    }[];
  };
  whenAndWhere: {
    title: string;
    subtitle: string;
    buttonLabel: string;
    image: string | Media;
    features: {
      emoji: string;
      title: string;
      description: string;
      id?: string | null;
    }[];
  };
  numbers: {
    title: string;
    numbers: {
      value: number;
      label: string;
      id?: string | null;
    }[];
  };
  faq: {
    title: string;
    questions: {
      question: string;
      answer: string;
      id?: string | null;
    }[];
  };
  cta2: {
    title: string;
    buttonLabel: string;
  };
  footer: {
    links: {
      label: string;
      url: string;
      id?: string | null;
    }[];
    socialLinks: {
      platform: 'Facebook' | 'YouTube' | 'LinkedIn' | 'Instagram';
      url: string;
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        buttonLabel?: T;
        partners?:
          | T
          | {
              logo?: T;
              name?: T;
              id?: T;
            };
      };
  nextGames?:
    | T
    | {
        title?: T;
        sportCategories?:
          | T
          | {
              name?: T;
              emoji?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonLabel?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        title?: T;
        statistics?:
          | T
          | {
              value?: T;
              label?: T;
              description?: T;
              id?: T;
            };
        image?: T;
      };
  testimonials?:
    | T
    | {
        title?: T;
        reviews?:
          | T
          | {
              quote?: T;
              author?: T;
              image?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonLabel?: T;
        sports?:
          | T
          | {
              name?: T;
              image?: T;
              selected?: T;
              id?: T;
            };
      };
  strangers?:
    | T
    | {
        title?: T;
        strangers?:
          | T
          | {
              name?: T;
              age?: T;
              bio?: T;
              sport?: T;
              image?: T;
              id?: T;
            };
      };
  whenAndWhere?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonLabel?: T;
        image?: T;
        features?:
          | T
          | {
              emoji?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  numbers?:
    | T
    | {
        title?: T;
        numbers?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        title?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  cta2?:
    | T
    | {
        title?: T;
        buttonLabel?: T;
      };
  footer?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}